spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name_attribute: response
          42seoul:
            authorization_uri: https://api.intra.42.fr/oauth/authorize
            token_uri: https://api.intra.42.fr/oauth/token/
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name_attribute: login

        registration:
          google:
            client-id: client-id
            client-secret: secret
            scope: profile,email
          naver:
            client-id: client-id
            client-secret: secret
            scope: name,email,profile_image
            redirect-uri: https://host:port/login/oauth2/code/naver
            authorization_grant_type: authorization_code
            client-name: Naver
          42seoul:
            client-id: client-id
            client-secret: client-secret
            scope: public
            redirect-uri: https://host:port/login/oauth2/code/42seoul
            authorization_grant_type: authorization_code