spring:
  config:
    activate:
      on-profile: local
  web:
    resources:
      cache:
        period: 0
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/openstudio?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  session:
    store-type: jdbc

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

server:
  servlet:
    session:
      cookie:
        http-only: false

openstudio:
  survey: http://구글폼주소
  cadetcount: 900

